### ISSUE TITLE
List all routes without documentation

### ISSUE THREAD

**Issue by fernandes** [zertico/apidoc#8]
@RamonHossein ,
please create a todo list with all routes that are without documentation, so we can focus on them and keep everything in sync ;)

thank you!

**Comment by RamonHossein** [comment]
MANAGER
- [x] GET /api/v1/manager/provider-softlayer-profile-clients #9 
- [x] POST /api/v1/manager/provider-softlayer-profile-clients #9 
- [x] GET /api/v1/manager/provider-softlayer-profile-clients/:id #9 
- [x] PATCH /api/v1/manager/provider-softlayer-profile-clients/:id #9 
- [x]  GET /api/v1/manager/provider-softlayer-profile #9 
- [x] PATCH /api/v1/manager/provider-softlayer-profile #9 

ADMIN
- [x] GET /api/v1/admin/catalog-components/:id #9 
- [x] GET /api/v1/admin/catalog-products/:id #9 
- [x] FILTER /api/v1/catalog-products (product_name, provider_name) #9 
- [x] GET /api/v1/admin/catalog-providers/:id #9 
- [x] GET /api/v1/admin/shop-plans #9 
- [x] POST /api/v1/admin/shop-price #9 

USER
- [x] POST /api/v1/shop-price #9

**Comment by fernandes** [comment]
thank you @RamonHossein !! now we are ready to keep rockin' :wink:
